FROM python:3.11-slim

WORKDIR /app

# Simple flask app requirements
RUN pip install flask requests

COPY ./frontend_flask /app/frontend_flask

EXPOSE 5000

ENV FLASK_APP=frontend_flask/app.py

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
